### PR TITLE
for @bewest, these are @channemann results

### PR DESCRIPTION
**Pull request by channemann**
Medtronic 723 v2.4A

Ran into an exception during `INFO:commands:XXX: READ cur page number:`, could be a link problem, will try again later.

### CODE REVIEW

**Comment by bewest** [comment]
Thanks! Looking briefly at the logs, it looks like we didn't get any data from the pump; not even "what model are you?"  I would try `mm-send-comm.py --init sleep 0`. Also make sure the stick is within 3 feet of the pump :-(

**Comment by bewest** [comment]
Also good job :-).  If you got this stuff running ok, I've started recommending @openaps to people as the primary interface to this project.  Keep posting questions/issues, it helps everyone.  Thanks again.

**Comment by channemann** [comment]
Thank, Ben. This was my first go at it. @loudnate very patiently walked me through step by step, but we ran out of time before we could debug the issue and get better logs. I was successful using @openaps commands, but some of them gave confusing results. I'll see what I can do this weekend.

**Comment by bewest** [comment]
No problem, looking at the logs, I'm curious how far the usb stick was from the pump, and what, if anything, might have been in between.  Sometimes I find I have to move my pump from eg, left hip to right hip in order to get it within range of the stick, but hard to tell.

From what it looks like, the code is successfully installed and running but for some reason, it hasn't established a connection with your pump. Usually this is due to physical properties, my body blocking transmission or being out of range, or setting the wrong SERIAL.

Feel free to post any hard to interpret message, I'm more than happy to lend some interpretation or change what happens to become more clear.

**Comment by channemann** [comment]
Actually, we had the pump on the floor just a few inches from the stick (which was in an RPi). We did make the connection and ran a slew of commands, both openaps and decoding-carelink, with some success (model returned "723", for example). It may have disconnected while we ran the status-quo command, however, as Nate hypothesized. I'll try again and see what I can get.

**Comment by loudnate** [comment]
Hmm yeah, I don't see any indication of success in these logs either. Since
we did get the key-press commands working at one point, it must have been a
temporary comms issue.

@bewest I think a successful run will yield the first sample data for a 723.

**Comment by channemann** [comment]
So I have it up and running again, and I am successfully using mm-press-key.py (so the comms are functional). Should I run ./status-quo.sh again? Is there something I can look for to see if it is successful? Or is there a similar test/logging script in OpenAPS that I should run instead?

**Comment by bewest** [comment]
Success.  Let's get you up and running on openaps.  If you're main objective is getting data from the pump, openaps is the best/easiest interface.  If there's stuff you'd like to do that the mm-tools can do that openaps cannot, just make a note of it and I'll implement it.

Openaps will keep all your data in a special git repo, dedicated to tracking your data.  I made an example one here: https://github.com/bewest/openaps-example  Most people are choosing to make private repos on github to share and track progress together.

**Comment by channemann** [comment]
So I have openaps running, but if I'm understanding you here, I should fork it instead and work in there? My lack of git / github experience is pretty apparent here ;-)

**Comment by bewest** [comment]
No need to fork it, if you've got openaps running, everything is good.  The `openaps init` command creates a new environment on your computer, and then you do all your work inside that environment.  To get your environment synced to github, you would create a new project on github, just for you, and then upload your environment to that project.  Feel free to jump in https://gitter.im/nightscout/intend-to-bolus for help/questions/chat. :-)

**Pull request merged**
