### PR TITLE
status-quo run with carelink csv for pump #736868

### PR DESCRIPTION
**Pull request by loudnate**

### CODE REVIEW

**Comment by bewest** [comment]
This is very helpful, thank you very very very very much!  I wonder if the community can help us methodically dissect the data into unit tests.

**Comment by bewest** [comment]
Wowowow, I noticed you included csv from carelink, which is incredibly generous, it is hard to thank you enough.

I noticed from the csv that you are also using the medtronic cgm?  We can collect cgm data using:

(after `mm-send-comm.py --init sleep 0` which should print the model number, if you have `export SERIAL=736868`)
```
# should print current glucose history page range
mm-send-comm.py tweak ReadCurGlucosePageNumber
mm-send-comm.py tweak --save ReadGlucoseHistory --page [...]
```

The page numbers will be arbitrary, and you can influence the filename of the path with `--prefix ./analysis/736868/`, which should save the `ReadHistoryGlucose-page-$x.data` with the rest of the files.

You can "render" the glucose files using `python list_cgm.py ./analysis/736868/ReadHistoryGlucose-page-$x.data | tee analysis/736868/ReadHistoryGlucose-$x.markdown`, or something similar.

I believe @erobinson, and @bustavo might have tips on this, they active users.

Hope this helps!

**Comment by bustavo** [comment]
Yes, I download bg data from the enlite cgm exactly the way you point out @bewest 

The only difference is I parse the output for the list_cgm.py to build arrays / hashes / etc.

There are a couple of issues I have posted where the data is unreadable when turning to a new page or when changing batteries... I've modified the list_cgm.py script to ignore some of the event types and it can read the history again only with an incorrect time ( by minutes )... 

If you have gotten around any of these please let me know! :)

Also, if you need help, let me know!

**Comment by bewest** [comment]
https://github.com/bewest/decoding-carelink/issues/66 for more info on debugging cgm history.

**Pull request merged**
