### PR TITLE
Wip/rename carelink names

### PR DESCRIPTION
**Pull request by bewest**

### CODE REVIEW

**Comment by bewest** [comment]
https://gist.github.com/ps2/bc4208080321c9a1b31b

**Comment by bewest** [comment]
### probably not
* [ ]   "BolusWizardBolusEstimate" => "BolusWizard",
* [ ]   "BolusNormal" => "Bolus"


### maybe
* [ ]    "JournalEntryPumpLowReservoir" => "LowReservoir",
* [ ]    "Suspend" => "PumpSuspend",
* [ ]    "Resume" => "PumpResume",

I think `LowReservoir` is a simpler name, but there's probably some value to making these match.

**Comment by loudnate** [comment]
FYI, Renaming suspend and resume will have a breaking effect on MMHistoryTools

**Comment by bewest** [comment]
Please keep an eye out for this, @openaps/contributors

**Pull request merged**
