### PR TITLE
Aliasing model number 723 to the 523 configuration

### PR DESCRIPTION
**Pull request by loudnate**

### CODE REVIEW

**Comment by loudnate** [comment]
Hey @bewest, there's a few ways to achieve the goal in this PR, and I'm happy to drive this one of the other ways if you prefer.

1. Alias 7xx to 5xx as each model is verified (this PR)
2. Create new `Model7xx` classes (subclassing from the `5xx` class)
3. Key the `known` dict without the first character of the model number (might be too broad of an assumption)

It looks like @amazaheri is looking to use `openaps` with a 722 and is running into a similar issue. (https://github.com/openaps/openaps/issues/11)

**Comment by bewest** [comment]
Let's get pedantic, and list out subclasses for all known types. :-)

**Comment by bewest** [comment]
I'm gathering all the work for next release in `bewest/dev`: https://github.com/bewest/decoding-carelink/pull/103

**Comment by loudnate** [comment]
Alright, PR updated! I added the 722 as a simple alias to the 522 in the hope it frees up @amazaheri to continue any debugging.

**Comment by amazaheri** [comment]
thumbs up!

**Comment by loudnate** [comment]
Closing in favor of #109

**Pull request closed without merging**
