### PR TITLE
refuse to run unless device is not in use

### PR DESCRIPTION
**Pull request by bewest**
Should refuse to run unless device is "free."

### CODE REVIEW

**Comment by loudnate** [comment]
:+1:

**Comment by bewest** [comment]
I could use some help testing this, actually.  Also, should there be a way to override/force it anyway (for some random testing/hacking/debugging need)?

**Comment by scottleibrand** [comment]
My main concern would be having a 100% reliable way to kill all of the
other processes using the carelink stick and releasing the lock on it so
your process can continue.

-Scot

**Comment by bewest** [comment]
Idea behind this is to avoid killing processes.  Instead, this will prevent new processes from running at all.  This should allow the pre-existing process to run to completion without having to worry about maintaining an external lock.  The lock might serve some other purpose for openaps loop semantics, but in terms of decocare, the goal here is avoid running at all if it's going to mess up the stick.  This will make it a lot easier to use the `mm-` tools along side a running loop without fear of corrupting the stick communications because it detects if the resource itself is already busy.

**Comment by scottleibrand** [comment]
I get that.  But occasionally processes get stuck, and you need a
super-reliable way to kill them off and start fresh, both for manual
testing purposes and automatically if you detect that no progress is being
made for like 10 minutes.

**Pull request merged**
